---
title: "PH_Linear_Regression"
author: "Doris Liu"
date: "10/19/2021"
output: html_document
---

```{r}
library(tidyverse)
library(janitor)
library(here)
ph_clean<- read_csv(here("data", "ph_clean.csv")) %>% 
  clean_names()
```

```{r}
Alegria <- dplyr::filter(ph_clean, site=="Alegria")  ## Filtering the data according to different sites
Lompoc_Landing <- dplyr::filter(ph_clean, site=="Lompoc Landing")
Bodega_Bay <- dplyr::filter(ph_clean, site=="Bodega Bay")
View(Bodega_Bay)
View(Lompoc_Landing)
View(Alegria)
```


```{r}
ggplotRegression <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red") +
  labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     "Intercept =",signif(fit$coef[[1]],5 ),
                     " Slope =",signif(fit$coef[[2]], 5),
                     " P =",signif(summary(fit)$coef[2,4], 5)))
}
```

Alegria: 12.37% of the total variation is explained by the predictors according to the R-squared. 
```{r}
Alegria_temp <- lm(formula = p_h ~ temp_c, data = Alegria) ## p_h vs temperature
summary(Alegria_temp)
ggplotRegression(lm(p_h ~temp_c, data = Alegria))
```
Lompoc Landing: 41.29% of the total variation is explained by the predictors according to the R-squared. 
```{r}
Lompoc_temp <- lm(formula = p_h ~ temp_c, data = Lompoc_Landing) ## p_h vs temperature
summary(Lompoc_temp)
ggplotRegression(lm(p_h ~ temp_c, data = Lompoc_Landing))
```
Bodega Bay: 16.54% of the total variation is explained by the predictors according to the R-squared. 
```{r}
Bodega_Bay_temp <- lm(formula = p_h ~ temp_c, data = Bodega_Bay) ## p_h vs temperature
summary(Bodega_Bay_temp)
ggplotRegression(lm(p_h ~temp_c , data = Bodega_Bay))
```

```{r}
Alegria_tide <- lm(formula = p_h ~ tide, data = Alegria) ## p_h vs tide
summary(Alegria_tide)
ggplotRegression(lm(p_h ~tide, data = Alegria))
```

```{r}
Lompoc_tide <- lm(formula = p_h ~ tide, data = Lompoc_Landing) ## p_h vs tide
summary(Lompoc_tide)
ggplotRegression(lm(p_h ~ tide, data = Lompoc_Landing))
```

```{r}
Bodega_Bay_tide <- lm(formula = p_h ~ tide, data = Bodega_Bay) ## p_h vs tide
summary(Bodega_Bay_tide)
ggplotRegression(lm(p_h ~tide, data = Bodega_Bay))
```